# Generated by Django 3.2.13 on 2022-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_auto_20220610_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='Articles.Tag'),
        ),
    ]
