# Generated by Django 3.2.13 on 2022-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_commit',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(null=True, upload_to='author'),
        ),
    ]
