# Generated by Django 3.2.13 on 2022-06-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_auto_20220610_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default=1, max_length=222),
            preserve_default=False,
        ),
    ]
