# Generated by Django 3.2.13 on 2022-06-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0008_remove_post_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
